import { sql } from 'kysely';
import type { Migration } from './index';

const FK_USER = 'TEXT REFERENCES user(id) ON DELETE SET NULL';

/** Booléen 0/1 ; `DEFAULT 0` sauf demande contraire. */
const bool = (col: string, withDefault = true) =>
  `${col} INTEGER NOT NULL${withDefault ? ' DEFAULT 0' : ''} CHECK (${col} IN (0,1))`;

/** Gabarit +SYNC (09 §0). */
const sync = () =>
  [
    'owner_id TEXT NOT NULL REFERENCES user(id) ON DELETE CASCADE',
    'rev INTEGER NOT NULL',
    'created_at TEXT NOT NULL',
    'updated_at TEXT NOT NULL',
    `updated_by ${FK_USER}`,
    'deleted_at TEXT',
  ].join(', ');

const table = (name: string, ...defs: string[]) => `CREATE TABLE ${name} (${defs.join(', ')}) STRICT`;

const TABLES: string[] = [
  table(
    'server_meta',
    'id INTEGER PRIMARY KEY CHECK (id = 1)',
    'server_epoch TEXT NOT NULL',
    'epoch_started_at TEXT NOT NULL',
    'epoch_base_rev INTEGER NOT NULL DEFAULT 0',
    'sync_counter INTEGER NOT NULL DEFAULT 0',
    'tombstone_purge_rev INTEGER NOT NULL DEFAULT 0',
    'catalog_version TEXT',
    'catalog_updated_at TEXT',
  ),
  table(
    'user',
    'id TEXT PRIMARY KEY',
    'username TEXT NOT NULL',
    'username_key TEXT NOT NULL UNIQUE',
    'password_hash TEXT NOT NULL',
    "role TEXT NOT NULL CHECK (role IN ('admin','member'))",
    "status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','disabled'))",
    'birth_date TEXT NOT NULL',
    'terms_version TEXT',
    'terms_accepted_at TEXT',
    'last_login_at TEXT',
    'password_changed_at TEXT',
    "onboarding_step TEXT CHECK (onboarding_step IN ('goal','sport','place_kind','place','experience','availability','health','ready'))",
    'onboarding_completed_at TEXT',
    'invitation_id TEXT REFERENCES invitation(id) ON DELETE SET NULL',
    'rev INTEGER NOT NULL',
    'created_at TEXT NOT NULL',
    'updated_at TEXT NOT NULL',
    `updated_by ${FK_USER}`,
  ),
  table(
    'invitation',
    'id TEXT PRIMARY KEY',
    'code_hash TEXT NOT NULL UNIQUE',
    'note TEXT CHECK (length(note) <= 60)',
    'birth_date TEXT',
    bool('is_admin_bootstrap'),
    `created_by ${FK_USER}`,
    'created_at TEXT NOT NULL',
    'expires_at TEXT NOT NULL',
    'used_at TEXT',
    `used_by ${FK_USER}`,
    'revoked_at TEXT',
  ),
  table(
    'applied_op',
    'op_id TEXT PRIMARY KEY',
    'user_id TEXT NOT NULL REFERENCES user(id) ON DELETE CASCADE',
    'entity TEXT NOT NULL',
    'row_id TEXT NOT NULL',
    "status TEXT NOT NULL CHECK (status IN ('applied','applied_partial','duplicate','rejected'))",
    'assigned_rev INTEGER',
    'applied_at TEXT NOT NULL',
  ),
  table(
    'sync_rejection',
    'id TEXT PRIMARY KEY',
    sync(),
    'op_id TEXT NOT NULL',
    'entity TEXT NOT NULL',
    'row_id TEXT NOT NULL',
    "code TEXT NOT NULL CHECK (code IN ('validation','forbidden','parent_rejected','stale_revision','unknown_entity','protocol'))",
    'detail_json TEXT CHECK (json_valid(detail_json))',
    'dismissed_at TEXT',
  ),
  table(
    'password_reset',
    'id TEXT PRIMARY KEY',
    'user_id TEXT NOT NULL REFERENCES user(id) ON DELETE CASCADE',
    'code_hash TEXT NOT NULL UNIQUE',
    `created_by ${FK_USER}`,
    'created_at TEXT NOT NULL',
    'expires_at TEXT NOT NULL',
    'used_at TEXT',
    'cancelled_at TEXT',
  ),
  table(
    'session',
    'id TEXT PRIMARY KEY',
    'token_hash TEXT NOT NULL UNIQUE',
    `user_id ${FK_USER}`,
    'created_at TEXT NOT NULL',
    'last_seen_at TEXT NOT NULL',
    'expires_at TEXT NOT NULL',
    bool('must_change_password'),
    'revoked_at TEXT',
    "revoked_reason TEXT CHECK (revoked_reason IN ('logout','logout_all','password_change','password_reset','admin','account_deleted'))",
  ),
  table(
    'consent_event',
    'id TEXT PRIMARY KEY',
    'owner_id TEXT NOT NULL REFERENCES user(id) ON DELETE CASCADE',
    "type TEXT NOT NULL CHECK (type IN ('health','ai_coach'))",
    "action TEXT NOT NULL CHECK (action IN ('grant','withdraw'))",
    'text_version TEXT NOT NULL',
    'rev INTEGER NOT NULL',
    'created_at TEXT NOT NULL',
    'updated_at TEXT NOT NULL',
    `updated_by ${FK_USER}`,
  ),
  table(
    'security_event',
    'id TEXT PRIMARY KEY',
    'at TEXT NOT NULL',
    'type TEXT NOT NULL',
    'actor_id TEXT',
    'target_id TEXT',
    'tailnet_ip TEXT',
    "outcome TEXT NOT NULL CHECK (outcome IN ('success','failure','blocked'))",
    'details TEXT CHECK (json_valid(details))',
  ),
  table(
    'training_profile',
    'id TEXT PRIMARY KEY',
    sync(),
    "goal TEXT CHECK (goal IN ('muscle','strength','fat_loss','fitness','sport_support'))",
    "experience TEXT CHECK (experience IN ('none','lt_6_months','6_to_24_months','gt_24_months'))",
    'days_per_week INTEGER CHECK (days_per_week BETWEEN 2 AND 4)',
    'session_minutes INTEGER CHECK (session_minutes IN (30,45,60,75,90))',
    'sport_code TEXT',
    'sport_other_label TEXT CHECK (length(sport_other_label) <= 40)',
    bool('cautious_mode'),
    'CHECK (id = owner_id)',
  ),
  table(
    'health_screening',
    'id TEXT PRIMARY KEY',
    sync(),
    'caution INTEGER CHECK (caution IN (0,1))',
    'questionnaire_version TEXT',
    'answered_at TEXT',
    'CHECK (id = owner_id)',
    'CHECK (deleted_at IS NOT NULL OR (caution IS NOT NULL AND questionnaire_version IS NOT NULL AND answered_at IS NOT NULL))',
  ),
  table(
    'limitation',
    'id TEXT PRIMARY KEY',
    sync(),
    "body_area TEXT CHECK (body_area IN ('shoulder','elbow','wrist_hand','neck','upper_back','lower_back','hip','knee','ankle_foot','other'))",
    "side TEXT CHECK (side IN ('left','right','both','not_applicable'))",
    "severity TEXT CHECK (severity IN ('mild','severe'))",
    'note TEXT CHECK (length(note) <= 200)',
    'active INTEGER CHECK (active IN (0,1))',
    'CHECK (deleted_at IS NOT NULL OR (body_area IS NOT NULL AND side IS NOT NULL AND severity IS NOT NULL AND active IS NOT NULL))',
  ),
  table(
    'gym',
    'id TEXT PRIMARY KEY',
    'name TEXT NOT NULL CHECK (length(name) BETWEEN 2 AND 60)',
    'name_key TEXT NOT NULL',
    'city TEXT NOT NULL CHECK (length(city) BETWEEN 2 AND 60)',
    'city_key TEXT NOT NULL',
    'load_settings TEXT NOT NULL CHECK (json_valid(load_settings))',
    `created_by ${FK_USER}`,
    `updated_by ${FK_USER}`,
    'rev INTEGER NOT NULL',
    'created_at TEXT NOT NULL',
    'updated_at TEXT NOT NULL',
    'deleted_at TEXT',
    'UNIQUE (name_key, city_key)',
  ),
  table(
    'gym_equipment',
    'id TEXT PRIMARY KEY',
    'gym_id TEXT NOT NULL REFERENCES gym(id) ON DELETE CASCADE',
    'equipment_code TEXT NOT NULL',
    `added_by ${FK_USER}`,
    'rev INTEGER NOT NULL',
    'created_at TEXT NOT NULL',
    'updated_at TEXT NOT NULL',
    'deleted_at TEXT',
    "CHECK (id = gym_id || ':' || equipment_code)",
  ),
  table(
    'gym_history',
    'id TEXT PRIMARY KEY',
    'gym_id TEXT NOT NULL REFERENCES gym(id) ON DELETE CASCADE',
    `author_id ${FK_USER}`,
    'at TEXT NOT NULL',
    "action TEXT NOT NULL CHECK (action IN ('create','update_info','add_equipment','remove_equipment','update_load_settings'))",
    'detail TEXT NOT NULL CHECK (json_valid(detail))',
  ),
  table(
    'place',
    'id TEXT PRIMARY KEY',
    sync(),
    "kind TEXT NOT NULL CHECK (kind IN ('gym','home'))",
    'gym_id TEXT REFERENCES gym(id)',
    'name TEXT CHECK (length(name) <= 30)',
    bool('is_primary'),
    bool('visible_at_gym'),
    'load_settings TEXT CHECK (json_valid(load_settings))',
    "CHECK (kind = 'home' OR load_settings IS NULL)",
    "CHECK ((kind = 'gym') = (gym_id IS NOT NULL))",
    "CHECK (kind = 'home' OR name IS NULL)",
  ),
  table(
    'home_equipment',
    'id TEXT PRIMARY KEY',
    'place_id TEXT NOT NULL REFERENCES place(id) ON DELETE CASCADE',
    'equipment_code TEXT NOT NULL',
    sync(),
    "CHECK (id = place_id || ':' || equipment_code)",
  ),
];

const OWNER_REV = [
  'sync_rejection',
  'consent_event',
  'training_profile',
  'health_screening',
  'limitation',
  'place',
  'home_equipment',
];
const REV = ['user', 'gym', 'gym_equipment', ...OWNER_REV];

const INDEXES: string[] = [
  ...REV.map((t) => `CREATE INDEX ${t}_rev_idx ON ${t} (rev)`),
  ...OWNER_REV.map((t) => `CREATE INDEX ${t}_owner_rev_idx ON ${t} (owner_id, rev)`),
  'CREATE INDEX applied_op_user_applied_idx ON applied_op (user_id, applied_at)',
  'CREATE INDEX consent_event_owner_type_created_idx ON consent_event (owner_id, type, created_at)',
  'CREATE INDEX security_event_at_idx ON security_event (at)',
  'CREATE INDEX password_reset_user_idx ON password_reset (user_id)',
  'CREATE INDEX session_user_idx ON session (user_id)',
  'CREATE INDEX gym_equipment_gym_idx ON gym_equipment (gym_id)',
  'CREATE INDEX gym_history_gym_at_idx ON gym_history (gym_id, at)',
  'CREATE INDEX place_gym_idx ON place (gym_id)',
  'CREATE INDEX home_equipment_place_idx ON home_equipment (place_id)',
  'CREATE UNIQUE INDEX place_owner_gym_uq ON place (owner_id, gym_id) WHERE deleted_at IS NULL',
  'CREATE UNIQUE INDEX place_owner_primary_uq ON place (owner_id) WHERE is_primary = 1 AND deleted_at IS NULL',
];

export const socle: Migration = {
  id: '0001_socle',
  breaking: false,
  up: async (db) => {
    for (const ddl of [...TABLES, ...INDEXES]) await sql.raw(ddl).execute(db);
  },
};
