import { z } from 'zod';

export const ApiErrorCode = z.enum([
  'validation',
  'unauthenticated',
  'invalid_credentials',
  'forbidden',
  'origin_mismatch',
  'unsupported_media_type',
  'account_disabled',
  'password_change_required',
  'health_consent_required',
  'reset_self_forbidden',
  'not_found',
  'conflict',
  'username_taken',
  'last_admin',
  'gym_duplicate',
  'gym_in_use',
  'place_exists',
  'last_place',
  'primary_required',
  'onboarding_incomplete',
  'password_rejected',
  'username_invalid',
  'under_min_age',
  'invitation_expired',
  'invitation_used',
  'invitation_revoked',
  'invitation_unknown',
  'reset_invalid',
  'account_deleted',
  'watermark_expired',
  'protocol_unsupported',
  'rate_limited',
  'internal',
]);
export type ApiErrorCode = z.infer<typeof ApiErrorCode>;

export const ERROR_STATUS: Record<ApiErrorCode, number> = {
  validation: 400,
  password_rejected: 400,
  username_invalid: 400,
  under_min_age: 400,
  invitation_expired: 400,
  invitation_used: 400,
  invitation_revoked: 400,
  invitation_unknown: 400,
  reset_invalid: 400,
  unauthenticated: 401,
  invalid_credentials: 401,
  forbidden: 403,
  origin_mismatch: 403,
  account_disabled: 403,
  password_change_required: 403,
  health_consent_required: 403,
  reset_self_forbidden: 403,
  not_found: 404,
  conflict: 409,
  username_taken: 409,
  last_admin: 409,
  gym_duplicate: 409,
  gym_in_use: 409,
  place_exists: 409,
  last_place: 409,
  primary_required: 409,
  onboarding_incomplete: 409,
  account_deleted: 410,
  watermark_expired: 410,
  unsupported_media_type: 415,
  protocol_unsupported: 426,
  rate_limited: 429,
  internal: 500,
};

export const ApiErrorBody = z.object({ error: ApiErrorCode }).passthrough();
export type ApiErrorBody = z.infer<typeof ApiErrorBody>;
